# Generated by Django 4.0.10 on 2025-03-04 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, choices=[('800m', '800m'), ('1500m', '1500m'), ('1mile', '1mile'), ('3000m', '3000m'), ('3000mSC', '3000mSC'), ('2mile', '2mile'), ('5000m', '5000m'), ('10000m', '10000m'), ('ハーフマラソン', 'ハーフマラソン'), ('フルマラソン', 'フルマラソン')], max_length=20, null=True)),
                ('best_time', models.CharField(blank=True, help_text='Format: hh:mm:ss for long distances, m\'ss"SS for middle distances', max_length=15, null=True)),
                ('recorded_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'specialty_event',
                'unique_together': {('user', 'event_name')},
            },
        ),
    ]
